### ISSUE TITLE
Homepage speakers section display on mobile

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#11]
Need your help to check this section on tablets: both portrait and landscape views. Various display issues on different size of screens.

<img width="772" alt="screen shot 2018-04-04 at 1 23 57 pm" src="https://user-images.githubusercontent.com/27847639/38332853-d55b71c6-380b-11e8-8881-eb5fdebe4e85.png">
<img width="770" alt="screen shot 2018-04-04 at 1 23 33 pm" src="https://user-images.githubusercontent.com/27847639/38332860-d9c0e318-380b-11e8-99bd-852b0a362076.png">

**Comment by jimwclement** [comment]
Hey Haokun,

#11 is not done yet, but notes/updates for all others can be seen below in
*bold*:

*In regards to* video*:*

   1. But the problem still is there: Video disappears after you closed out
   the popup.
   *- This will not popup then as that is coming from the Wistia settings. *
2. Can we make the video preview box regular video 16:9 proportion? The box
   right now is a weird size.

*- Same as #1 *
   3. Can we enable this video on mobile too? Both phone and tablets.
   *- Updated.*


*Footer CTA*: Footer CTA has a similar problem we had before on both phone
and tablet view. Need boarders.
*- Updated. http://prntscr.com/j11nko
<http://click.accelo.com/wf/click?upn=wm89Nmzj1Zraj6M2eLYUaluOuJDgjN8YcFv0Oxs6ej8-3D_J89cLGTOSsFxVMV9boVRCRTiacfN-2Bzvjp6to1fZA5ffE8d4C8SCY7ishwxBVeslucEP-2BmI1OplmfO55DLURcUGTlyy8Acy8y-2BwXHvD71kyeFsuattUV34D-2F5NXF-2FONNr8SN1IhDZ6Zuko-2FV7dZKY5wMEQYHsNlrIOFRa1RpGtGWcEcmltys3Eo84-2B8r6iLXKxkky474Oupn9k-2B2JFmPDt0Y9giu1Wb-2B8JDOEiLzY8Sd4fKnZa6gfnASJXWYbi65hzoRDfo-2Bpw5Bn28yjBaUha7trHmCNrhbKC4RBgL6LcQDBA-2Fc0V0HtlTPk3YwSE0sLuSUjGmXx0NcA9n3WoyAk6A-3D-3D>*

*Nav: mobile landscape view needs improvement*
Mobile: http://prntscr.com/j0xw8g
<http://click.accelo.com/wf/click?upn=wm89Nmzj1Zraj6M2eLYUalYX4iNl-2FSulULWkKDba25Q-3D_J89cLGTOSsFxVMV9boVRCRTiacfN-2Bzvjp6to1fZA5ffE8d4C8SCY7ishwxBVeslucEP-2BmI1OplmfO55DLURcUGTlyy8Acy8y-2BwXHvD71kyeFsuattUV34D-2F5NXF-2FONNr8SN1IhDZ6Zuko-2FV7dZKY5wMEQYHsNlrIOFRa1RpGtGWcEcmltys3Eo84-2B8r6iLXKYCpVwwXRQfT-2F7xbn6wexeMw8Alhzw2l4Cz52cKP8ufC0JrIEB817smE2hHBg-2F5DljqL87ddD3vAGJJH2E8DNFcyiSKdMh7fcQ2E6pjdlbqhC6x0mqCM-2FxkxvlBF2Tj2ZC8408kuKQP-2FEsrhm7KyvlQ-3D-3D>
Tablet: http://prntscr.com/j0xwdg
<http://click.accelo.com/wf/click?upn=wm89Nmzj1Zraj6M2eLYUai9z7RhMvmzeU-2FTwoCWO0SY-3D_J89cLGTOSsFxVMV9boVRCRTiacfN-2Bzvjp6to1fZA5ffE8d4C8SCY7ishwxBVeslucEP-2BmI1OplmfO55DLURcUGTlyy8Acy8y-2BwXHvD71kyeFsuattUV34D-2F5NXF-2FONNr8SN1IhDZ6Zuko-2FV7dZKY5wMEQYHsNlrIOFRa1RpGtGWcEcmltys3Eo84-2B8r6iLXK6UcFqBs3Y68t-2B7MSzXRUOrgF2thc-2Fd9ITkU5yuLfoiM-2BlifsZ6u1k0azSFHpwdM0JW3ZhAEN2CAchpPgGS5dDi3QsEmqewqYFDLjCnrvZLWNgybOH4eoGrQ5FuDDKOeDAQ-2BG4BNOVzwnRs9U-2FEz1MA-3D-3D>
*- Updated.*


Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On April 4, 2018 at 3:27:44 PM, Haokun Wang (notifications@github.com)
wrote:

Need your help to check this section on tablets: both portrait and
landscape views. Various display issues on different size of screens.

[image: screen shot 2018-04-04 at 1 23 57 pm]
<https://user-images.githubusercontent.com/27847639/38332853-d55b71c6-380b-11e8-8881-eb5fdebe4e85.png>

[image: screen shot 2018-04-04 at 1 23 33 pm]
<https://user-images.githubusercontent.com/27847639/38332860-d9c0e318-380b-11e8-99bd-852b0a362076.png>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/haokunw/kintoneconnect/issues/11>, or mute the thread
