### ISSUE TITLE
Homepage mobile background

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#14]
Hi Jim, seems like the slider is showing up on the mobile view. We'd hope to disable the image slider on mobile. In the meantime, the background on mobile should be this image http://www.kintoneconnect.com/wp-content/uploads/2018/04/Kintone-Connect-2018-mobile.png

![screen shot 2018-04-18 at 1 09 27 pm](https://user-images.githubusercontent.com/27847639/38955514-ca78651c-4309-11e8-8ee7-22a74a268986.png)

**Comment by jimwclement** [comment]
Hey Haokun,

Sorry for the delay.

Please see my updates below:

1. I can't recreate the problem on any other computers, but there's this
computer having display issue.
*- Updated. Clear cache and cookie before checking please. *

2. Seems like the slider is showing up on the mobile view. We'd hope to
disable the image slider on mobile. In the meantime, the background on
mobile should be this image
http://www.kintoneconnect.com/wp-content/uploads/2018/04/Kintone-Connect-2018-mobile.png

*- Updated. No video on mobile.*

Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On April 18, 2018 at 3:10:12 PM, Haokun Wang (notifications@github.com)
wrote:

Hi Jim, seems like the slider is showing up on the mobile view. We'd hope
to disable the image slider on mobile. In the meantime, the background on
mobile should be this image
http://www.kintoneconnect.com/wp-content/uploads/2018/04/Kintone-Connect-2018-mobile.png

[image: screen shot 2018-04-18 at 1 09 27 pm]
<https://user-images.githubusercontent.com/27847639/38955514-ca78651c-4309-11e8-8ee7-22a74a268986.png>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/haokunw/kintoneconnect/issues/14>, or mute the thread

**Comment by haokunw** [comment]
We actually want the video on mobile too. Just not the slider. Is it possible? Thank you

**Comment by jimwclement** [comment]
Okay updated that on mobile.

Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On April 19, 2018 at 11:15:16 AM, Haokun Wang (notifications@github.com)
wrote:

We actually want the video on mobile too. Just not the slider. Is it
possible? Thank you

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/haokunw/kintoneconnect/issues/14#issuecomment-382794594>,
or mute the thread

**Comment by haokunw** [comment]
Looking great. Thank you!
