### ISSUE TITLE
Homepage: Above the fold design change

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#15]
Example: https://www.box.com/boxworks/ 

We'd like to switch to:
1. Video background
2. Event name and date be similar to Box Works
3. Two buttons
4. Right under the two buttons, a tagline saying "A Day Rocking Your Career"

For mobile view, we can keep what we have right now. Only changing the background to a solid red (#ef3f24)

**Comment by haokunw** [comment]
@jimwclement 

1. Can we make the background even darker? 

2. The buttons are not aligned.

<img width="1351" alt="screen shot 2018-08-01 at 9 57 23 am" src="https://user-images.githubusercontent.com/27847639/43536413-65550432-9571-11e8-90a4-20122a79334d.png">

3. Can we add weight to the button text?

4. Can we add white border to both buttons so that they pop more?

5. Oh, can we make the video auto play? 

Thank you!

**Comment by jimwclement** [comment]
Will do thanks!


Thanks,
Jim Clement - Project Manager & Developer
screen shot 2018-08-01 at 9 57 23 am 
( http://www.millennialwebdevelopment.com/ )
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
( https://github.com/haokunw/kintoneconnect/issues/15#issuecomment-409646226 )
, or mute the thread

**Comment by haokunw** [comment]
![screen shot 2018-08-02 at 2 58 30 pm](https://user-images.githubusercontent.com/27847639/43613612-e6521932-9664-11e8-84cb-0949400a154c.png)

The red background isn't covering the whole screen.

Also, can we add more space above the "A Day Rocking Your Career" tagline? Thanks!

**Comment by jimwclement** [comment]
Hey Haokun,

Updates below in bold:

The red background isn't covering the whole screen.
- Updated.

Also, can we add more space above the "A Day Rocking Your Career"
tagline? Thanks!
- Updated.

Happy Friday!



Thanks,
Jim Clement - Project Manager & Developer
screen shot 2018-08-02 at 2 58 30 pm 
( http://www.millennialwebdevelopment.com/ )
The red background isn't covering the whole screen.
Also, can we add more space above the "A Day Rocking Your Career"
tagline? Thanks!
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
( https://github.com/haokunw/kintoneconnect/issues/15#issuecomment-410081779 )
, or mute the thread
