### ISSUE TITLE
Homepage: speakers' faces cut off

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#20]
Can we adjust the banner so that speakers' faces won't get cut off? Thanks!

<img width="1439" alt="screen shot 2018-07-26 at 2 01 02 pm" src="https://user-images.githubusercontent.com/27847639/43288407-92cd246a-90dc-11e8-8b83-f9888536cbc5.png">

**Comment by jimwclement** [comment]
Thanks for sending.


Thanks,
Jim Clement - Project Manager & Developer
screen shot 2018-07-26 at 2 01 02 pm 
( http://www.millennialwebdevelopment.com/ )
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub 
( https://github.com/haokunw/kintoneconnect/issues/20 ), or mute
the thread
