### ISSUE TITLE
New template: Landing Page

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#25]
We'll need a new template for completely new contents. Here's a simple mockup. Would you please help put up something before EOW? 

Let me know if you have any questions. Thanks!

![kc lp mockup](https://user-images.githubusercontent.com/27847639/44753932-b5854980-aad4-11e8-834f-cc4071e1863f.png)

**Comment by haokunw** [comment]
https://www.kintoneconnect.com/npo/

<img width="1235" alt="screen shot 2018-09-10 at 9 11 03 am" src="https://user-images.githubusercontent.com/27847639/45309852-88c03180-b4d9-11e8-980d-68f4ec2ae1de.png">

Can we align the three icons and their title and content?

Also, for the stay tuned button, can we make it the same popup as this one?

<img width="1318" alt="screen shot 2018-09-10 at 9 15 35 am" src="https://user-images.githubusercontent.com/27847639/45310063-24ea3880-b4da-11e8-9938-79d6c4f1447d.png">

<img width="1316" alt="screen shot 2018-09-10 at 9 15 42 am" src="https://user-images.githubusercontent.com/27847639/45310069-29aeec80-b4da-11e8-921f-f7713be27e66.png">

Thank you!

**Comment by haokunw** [comment]
Hi @jimwclement , love these changes!

Can we add more space between the title and image? 

![screen shot 2018-09-18 at 11 46 08 am](https://user-images.githubusercontent.com/27847639/45709261-788efe80-bb38-11e8-8c1f-b56907f111c8.png)

For the popup, I like how it is now. But seems like users need to click on the popup to be able to see the eventbrite page. Would you please investigate and see if we can take out the extra step?

Also, what I originally meant was adding a "Sign Up" button next to the register button. When people click on the sign up button, a popup will appear (we've already have this) to capture their name and email.

Thank you!

**Comment by jimwclement** [comment]
Hey Haokun,

Please see my updates below in bold:

Can we add more space between the title and image?
- Updated. http://prntscr.com/kw4h9b ( http://prntscr.com/kw4h9b ) 

For the popup, I like how it is now. But seems like users need to
click on the popup to be able to see the eventbrite page. Would
you please investigate and see if we can take out the extra step?
- We can't modify that because its an embed iframe from
eventbrite.

Also, what I originally meant was adding a "Sign Up" button next
to the register button. When people click on the sign up button,
a popup will appear (we've already have this) to capture their
name and email.
- Updated. http://prntscr.com/kw4jg5 ( http://prntscr.com/kw4jg5 ) 


Thanks,
Jim Clement - Project Manager & Developer
screen shot 2018-09-18 at 11 46 08 am 
( http://www.millennialwebdevelopment.com/ )
For the popup, I like how it is now. But seems like users need to
click on the popup to be able to see the eventbrite page. Would
you please investigate and see if we can take out the extra step?
Also, what I originally meant was adding a "Sign Up" button next
to the register button. When people click on the sign up button,
a popup will appear (we've already have this) to capture their
name and email.
Thank you!
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
( https://github.com/haokunw/kintoneconnect/issues/25#issuecomment-422505536 )
, or mute the thread
