### ISSUE TITLE
Homepage speakers display messed up

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#27]
See screenshot

<img width="1311" alt="screen shot 2018-09-19 at 11 40 59 am" src="https://user-images.githubusercontent.com/27847639/45932917-e2444980-bf38-11e8-8d7f-c99467442185.png">

**Comment by jimwclement** [comment]
Hey Haokun,

I see this on the url.  Did someone change the DNS?
http://prntscr.com/ky5qu6


Thanks,
Jim Clement - Project Manager & Developer
( http://www.millennialwebdevelopment.com/ )
P: (773) 576-0428
E: jimc@millennialwebdevelopment.com


On September 23, 2018 at 3:59 PM, Haokun Wang
(notifications@github.com) wrote:

Assigned #27 
( https://github.com/haokunw/kintoneconnect/issues/27 ) to
@jimwclement ( https://github.com/jimwclement ).
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub 
( https://github.com/haokunw/kintoneconnect/issues/27#event-1862134090 )

, or mute the thread

**Comment by haokunw** [comment]
@jimwclement yea, we saw the same thing since this morning. Our IT team is looking into this issue now. Thanks for letting me know!

**Comment by haokunw** [comment]
@jimwclement are you still seeing the error screen? It now should be automatically redirected to https://www.kintoneconnect.com

**Comment by jimwclement** [comment]
Yes, I see the site live now.


Thanks,
Jim Clement - Project Manager & Developer
( http://www.millennialwebdevelopment.com/ )
P: (773) 576-0428
E: jimc@millennialwebdevelopment.com


On September 26, 2018 at 2:37 PM, Haokun Wang
(notifications@github.com) wrote:

@jimwclement ( https://github.com/jimwclement ) are you still
seeing the error screen? It now should be automatically
redirected to https://www.kintoneconnect.com
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
( https://github.com/haokunw/kintoneconnect/issues/27#issuecomment-424843091 )
, or mute the thread

**Comment by haokunw** [comment]
@jimwclement Awesome. Would you please help up fix the speaker photos on the homepage? Thanks!

**Comment by jimwclement** [comment]
Hey Haokun,

Just updated those images.


Thanks,
Jim Clement - Project Manager & Developer
( http://www.millennialwebdevelopment.com/ )
P: (773) 576-0428
E: jimc@millennialwebdevelopment.com


On September 26, 2018 at 2:42 PM, Haokun Wang
(notifications@github.com) wrote:

@jimwclement ( https://github.com/jimwclement ) Awesome. Would
you please help up fix the speaker photos on the homepage?
Thanks!
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
( https://github.com/haokunw/kintoneconnect/issues/27#issuecomment-424844544 )
, or mute the thread

**Comment by haokunw** [comment]
Awesome, thank you!
