### ISSUE TITLE
Static image behind the video

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#28]
Seems like there's a static image behind the video showing up on certain screen size:

![screen shot 2018-10-02 at 4 48 44 pm](https://user-images.githubusercontent.com/27847639/46564266-216c8600-c8bb-11e8-8159-6f3d580c5dce.png)

screen is 20x12'

**Comment by jimwclement** [comment]
Hey Haokun,

Just updated that.  Can you please check again?


Thanks,
Jim Clement - Project Manager & Developer
screen shot 2018-10-02 at 4 48 44 pm 
( http://www.millennialwebdevelopment.com/ )
screen is 20x12'
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
( https://github.com/haokunw/kintoneconnect/issues/28 ), or mute
the thread
