### ISSUE TITLE
Homepage: video doesn't fully play

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#29]
The video stops playing and turns to a grey screen after about 10 secs

**Comment by jimwclement** [comment]
Hey Haokun,

I just updated that so it should be working now.  Please clear
your cache before you check. https://www.kintoneconnect.com


Thanks,
Jim Clement - Project Manager & Developer
( http://www.millennialwebdevelopment.com/ )
P: (773) 576-0428
E: jimc@millennialwebdevelopment.com


On October 14, 2018 at 10:11 PM, Haokun Wang
(notifications@github.com) wrote:

Assigned #29 
( https://github.com/haokunw/kintoneconnect/issues/29 ) to
@jimwclement ( https://github.com/jimwclement ).
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub 
( https://github.com/haokunw/kintoneconnect/issues/29#event-1902986586 )

, or mute the thread

**Comment by haokunw** [comment]
Looks good now. Thanks!
