### ISSUE TITLE
Speaker page: make the name font smaller

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#30]
Some of the speakers' names are too long and they go out of the red border box. Please help us tweak it.

Oh, and can we move the name+title down a bit altogether? Thanks

**Comment by jimwclement** [comment]
Hey Haokun,

Just updated that on the site.  Please clear your cache before
you check.


Thanks,
Jim Clement - Project Manager & Developer
( http://www.millennialwebdevelopment.com/ )
P: (773) 576-0428
E: jimc@millennialwebdevelopment.com


On October 18, 2018 at 12:41 PM, Haokun Wang
(notifications@github.com) wrote:

Assigned #30 
( https://github.com/haokunw/kintoneconnect/issues/30 ) to
@jimwclement ( https://github.com/jimwclement ).
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub 
( https://github.com/haokunw/kintoneconnect/issues/30#event-1912909485 )

, or mute the thread

**Comment by haokunw** [comment]
Awesome, thanks!
