### ISSUE TITLE
Video disappears after you closed out the popup

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#7]
Would be nice to have the video thumbnail stay after you close out the popup

**Comment by haokunw** [comment]
Hi Jim, we're ready to put the video up on the homepage! Video preview can be moved even a little further down. I'll leave it to you to decide the position. Thank you

![screen shot 2018-04-03 at 5 06 57 pm](https://user-images.githubusercontent.com/27847639/38281839-9a25fee6-3761-11e8-8ea3-7b226c6b8d52.png)

**Comment by jimwclement** [comment]
Hey Haokun,

The video is readded: https://prnt.sc/j0vr49

Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On April 3, 2018 at 7:08:48 PM, Haokun Wang (notifications@github.com)
wrote:

Hi Jim, we're ready to put the video up on the homepage! Thank you

[image: screen shot 2018-04-03 at 5 06 57 pm]
<https://user-images.githubusercontent.com/27847639/38281839-9a25fee6-3761-11e8-8ea3-7b226c6b8d52.png>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/haokunw/kintoneconnect/issues/7#issuecomment-378438092>,
or mute the thread

**Comment by haokunw** [comment]
Saw the changes. Thank you!

1. But the problem still is there: Video disappears after you closed out the popup.
2. Can we make the video preview box regular video 16:9 proportion? The box right now is a weird size.
3. Can we enable this video on mobile too? Both phone and tablets.

**Comment by haokunw** [comment]
Hi Jim,

  "1. But the problem still is there: Video disappears after you closed out
   the popup.
   *- This will not popup then as that is coming from the Wistia settings. 

2. Can we make the video preview box regular video 16:9 proportion? The box
   right now is a weird size."


Can we change the Wistia settings to make it work?

We have other Wistia video embeds and they look ok. Examples here: 

https://resources.kintone.com/modernize-workflow-demo-thank-you
https://resources.kintone.com/thank-you

Thank you

**Comment by jimwclement** [comment]
Need your help to check this section on tablets: both portrait and
landscape views. Various display issues on different size of screens.
*- Updated. http://prntscr.com/j1d8ip
<http://click.accelo.com/wf/click?upn=wm89Nmzj1Zraj6M2eLYUagZuma1-2BUy3GBqAJ1hcA5ME-3D_J89cLGTOSsFxVMV9boVRCRTiacfN-2Bzvjp6to1fZA5ffE8d4C8SCY7ishwxBVeslucEP-2BmI1OplmfO55DLURcUGTlyy8Acy8y-2BwXHvD71kyeFsuattUV34D-2F5NXF-2FONNr8SN1IhDZ6Zuko-2FV7dZKY5zaOBLBahMR74DjEMSbqKKNOfnpm7oAVgcv9aVwBqMv0v1AeNQRFF5kXvDw5px4N6CEdfQbp88-2FNGTNZ3296-2B9elGfocF4asPOrwqdKJNpsUe6t8q0fMXpDN4v-2BLquDnuVhCZPgUFOWRSvigDOOe-2Bqex9-2B-2F0rW4xnqu-2FAI2G-2FUkveY3N5Rgzz5QZ24fewYD4uw-3D-3D>*

1. But the problem still is there: Video disappears after you closed out
the popup.
*- This will not popup then as that is coming from the Wistia settings.

   1. Can we make the video preview box regular video 16:9 proportion? The
   box
   right now is a weird size."


*- Please let me know what then best width and height are in that case,
since I set this based on wistia.com <http://wistia.com> auto height and
width.*

Can we change the Wistia settings to make it work?

We have other Wistia video embeds and they look ok. Examples here:
https://resources.kintone.com/modernize-workflow-demo-thank-you
<http://click.accelo.com/wf/click?upn=7tQN5cglTVk2z6aJ-2F5HXqzf9TDVkUnu0d3Qgiu17Kpl5aI2yZZDcUCxtGxGAfyIp1UpmupGSYzRRIg8Vcbb9Tv6V-2BXvsrxvkw4kbabuYTF0-3D_J89cLGTOSsFxVMV9boVRCRTiacfN-2Bzvjp6to1fZA5ffE8d4C8SCY7ishwxBVeslucEP-2BmI1OplmfO55DLURcUGTlyy8Acy8y-2BwXHvD71kyeFsuattUV34D-2F5NXF-2FONNr8SN1IhDZ6Zuko-2FV7dZKY5zaOBLBahMR74DjEMSbqKKNOfnpm7oAVgcv9aVwBqMv0DMM9tJeeUUQdUHzZ-2F-2BPB-2F6Fzx0RQLUpWpj3nVdFaGuC7Yb4BOT95q20TfvX7gTBMMKe7Vgcc7H-2FhlflJ6j2Oih0pGv7Lg8SGBWvil7qrm5vzRfSjKYqOl72uGlWIsNGGted7EohMoKa1b96kiU5Few-3D-3D>
https://resources.kintone.com/thank-you
<http://click.accelo.com/wf/click?upn=7tQN5cglTVk2z6aJ-2F5HXqzf9TDVkUnu0d3Qgiu17Kpn1Ee0Yw9am-2BZBR2Gyz702R_J89cLGTOSsFxVMV9boVRCRTiacfN-2Bzvjp6to1fZA5ffE8d4C8SCY7ishwxBVeslucEP-2BmI1OplmfO55DLURcUGTlyy8Acy8y-2BwXHvD71kyeFsuattUV34D-2F5NXF-2FONNr8SN1IhDZ6Zuko-2FV7dZKY5zaOBLBahMR74DjEMSbqKKNOfnpm7oAVgcv9aVwBqMv0h-2FCpLNeH0EMP1cT5F-2F-2B89-2B3PeY1BSSMjYTYCozhlkb-2FnBomNa-2BjsEg8bQ0Em1lj6S6tkKG1DRebEq7AK84xgCrPdqf1aPVMCNUaRxfNKAuQhy6zTM9SLiEdxZ4i8r8T6XAEo6LhitmfTr3buHDqO3A-3D-3D>

*- What setting is that in Wistia? I only grabbed the embed code.  Not sure
why its gone. *


Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On April 5, 2018 at 12:13:19 PM, Haokun Wang (notifications@github.com)
wrote:

Hi Jim,

"1. But the problem still is there: Video disappears after you closed out
the popup.
*- This will not popup then as that is coming from the Wistia settings.

   1. Can we make the video preview box regular video 16:9 proportion? The
   box
   right now is a weird size."

Can we change the Wistia settings to make it work?

We have other Wistia video embeds and they look ok. Examples here:

https://resources.kintone.com/modernize-workflow-demo-thank-you
https://resources.kintone.com/thank-you

Thank you

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/haokunw/kintoneconnect/issues/7#issuecomment-379009303>,
or mute the thread

**Comment by haokunw** [comment]
Hmm.... It's the same with every video. Grabbed the embed code. Did you choose the popover option?

**Comment by jimwclement** [comment]
Hey Haokun,

This is the Wistia code: http://prntscr.com/j1tqw5
<http://click.accelo.com/wf/click?upn=wm89Nmzj1Zraj6M2eLYUar9J8Gyb88K1L9Oaz8sFklk-3D_J89cLGTOSsFxVMV9boVRCRTiacfN-2Bzvjp6to1fZA5ffE8d4C8SCY7ishwxBVeslucEP-2BmI1OplmfO55DLURcUGTlyy8Acy8y-2BwXHvD71kyeFsuattUV34D-2F5NXF-2FONNr8SN1IhDZ6Zuko-2FV7dZKY58-2BY-2BL-2BcM5ZYC8FKTkBtrg0SCKAmm3Lm5DVbYOQls3p64JSGZYqJ8kaENtTWm9TH9JdQP-2BA2p-2BBfYMZxdBlQK04yWy89-2Bv-2Bq7qI4a7RNiiI5iJS25Wtaph-2FofxfelUurWXqsnt63V4q7EV7Qn-2FIIk5bccQdvkoTyV8C-2BeE4Bz0NVPYN9Brbzoatzy-2BPzr0EEPw-3D-3D>

http://www.kintoneconnect.com/
<http://click.accelo.com/wf/click?upn=5deYF4nRqwWI2BVO4mbtGScNl4x-2FJJkVqkmJtd44YKxBx5xCj-2Bvvh-2BqWu4cafGy9_J89cLGTOSsFxVMV9boVRCRTiacfN-2Bzvjp6to1fZA5ffE8d4C8SCY7ishwxBVeslucEP-2BmI1OplmfO55DLURcUGTlyy8Acy8y-2BwXHvD71kyeFsuattUV34D-2F5NXF-2FONNr8SN1IhDZ6Zuko-2FV7dZKY58-2BY-2BL-2BcM5ZYC8FKTkBtrg0SCKAmm3Lm5DVbYOQls3p6kkIGtPI-2B5YBpydEQN44dNJeyj4ATBKdpWvpyJiiUoIYK5291NDT-2FJnwSwuATN9RiegHbzXwX0lMneUPfpJYARtVJ6GH-2FoBWpUBfN5mQo7zbOVvGc48vEqt5j6I7IOXjsJ-2FUod32tp-2FcEuDiEsZrA-2Bw-3D-3D>
and it shows like this: http://prntscr.com/j1ts4y Does this work?

Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On April 5, 2018 at 1:18:00 PM, Haokun Wang (notifications@github.com)
wrote:

Hmm.... It's the same with every video. Grabbed the embed code. Did you
choose the popover option?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/haokunw/kintoneconnect/issues/7#issuecomment-379029919>,
or mute the thread

**Comment by haokunw** [comment]
Hmm.... our team still prefers to have the regular 16:9 proportion. If the popup style can't work, we can keep what you did yesterday.

**Comment by jimwclement** [comment]
*Updated: http://prntscr.com/j1u0qo
<http://click.accelo.com/wf/click?upn=wm89Nmzj1Zraj6M2eLYUat-2BmE00SOAq-2FufzJHYI1gCY-3D_J89cLGTOSsFxVMV9boVRCRTiacfN-2Bzvjp6to1fZA5ffE8d4C8SCY7ishwxBVeslucEP-2BmI1OplmfO55DLURcUGTlyy8Acy8y-2BwXHvD71kyeFsuattUV34D-2F5NXF-2FONNr8SN1IhDZ6Zuko-2FV7dZKY541gIJ04TqdbGZMEo48fD0hHe2CRdiTU5LLK0H3WIN7xFPA95HCKqkxCsXgahITZP8m9FNWBJ4dyGWbws-2BIykzEHaa8SKZASFHSuLm46LoOJgXGXySuN7D8FueWcpQPkgHQ393aQ-2FhcwtxJ2XzFUT1POtPgujxdQH-2FXl6nWhOD9IWaMYDbT-2BihB1UW6uhulQCw-3D-3D>*

*Regarding Proportions:*
*- http://prntscr.com/j1u1s8 <http://prntscr.com/j1u1s8> its the
same** http://prntscr.com/j1u21u
<http://click.accelo.com/wf/click?upn=wm89Nmzj1Zraj6M2eLYUasQtFkmTb-2BS-2BSjvESKKJHNg-3D_J89cLGTOSsFxVMV9boVRCRTiacfN-2Bzvjp6to1fZA5ffE8d4C8SCY7ishwxBVeslucEP-2BmI1OplmfO55DLURcUGTlyy8Acy8y-2BwXHvD71kyeFsuattUV34D-2F5NXF-2FONNr8SN1IhDZ6Zuko-2FV7dZKY541gIJ04TqdbGZMEo48fD0hHe2CRdiTU5LLK0H3WIN7xy9qbReMkgcg-2F-2BTfz3TNvV-2FGdl7-2F79RLY2QOi-2FxHInJDmHr7vMsPa8gDPuuYLhzMdeqakvLCaL4Vcbp5IFFtyTd-2BQYN0Xw6fhhfQOLn9pbBKT5ap-2B3ZBBvP0xM4wRlp7UIGQ04i9tk0UNKNCTuubKvw-3D-3D>
This
is 16:9.  I just cannot set this as a popup. *

Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On April 6, 2018 at 12:09:52 PM, Haokun Wang (notifications@github.com)
wrote:

Hmm.... our team still prefers to have the regular 16:9 proportion. If the
popup style can't work, we can keep what you did yesterday.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/haokunw/kintoneconnect/issues/7#issuecomment-379316783>,
or mute the thread

**Comment by haokunw** [comment]
Oh well, let's keep it inline then. What we have now is good. Thank you
