### ISSUE TITLE
New page: why attend

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#8]
I played around with setting up a new template but don't know how to push the template to WP. Basically, we want to have:

1. An intro paragraph
2. An image slider 
3. A video gallery

Let me know if you have any questions.

**Comment by jimwclement** [comment]
Okay I will take a shot at creating one.

Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On March 29, 2018 at 12:30:03 PM, Haokun Wang (notifications@github.com)
wrote:

Assigned #8 <https://github.com/haokunw/kintoneconnect/issues/8> to
@jimwclement <https://github.com/jimwclement>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/haokunw/kintoneconnect/issues/8#event-1548407972>, or mute
the thread

**Comment by haokunw** [comment]
Hi Jim, quickly following up to see when will this page be ready? Thank you!
