### ISSUE TITLE
Mobile (both phone and tablet), portrait: CTA button need white boarders

### ISSUE THREAD

**Issue by haokunw** [haokunw/kintoneconnect#9]
Footer CTA has a similar problem we had before on both phone and tablet view. Need boarders

<img width="519" alt="screen shot 2018-04-04 at 12 57 58 pm" src="https://user-images.githubusercontent.com/27847639/38332133-10524784-380a-11e8-9b1b-e70335577d32.png">

**Comment by haokunw** [comment]
Just wanting to quickly check in and see how's this ticket coming along?

**Comment by jimwclement** [comment]
Will do and get back to you.

Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On April 19, 2018 at 1:20:20 PM, Haokun Wang (notifications@github.com)
wrote:

Just wanting to quickly check in and see how's this ticket coming along?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/haokunw/kintoneconnect/issues/9#issuecomment-382833290>,
or mute the thread

**Comment by jimwclement** [comment]
This issue is now fixed.  Thanks and have a great weekend.

Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On April 19, 2018 at 2:33:13 PM, Jim Clement (
jimc@millennialwebdevelopment.com) wrote:

Will do and get back to you.

Thanks,
*Jim Clement* - *Project Manager & Developer*

<http://www.millennialwebdevelopment.com/>

P: (773) 576-0428
E: jimc@millennialwebdevelopment.com

On April 19, 2018 at 1:20:20 PM, Haokun Wang (notifications@github.com)
wrote:

Just wanting to quickly check in and see how's this ticket coming along?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/haokunw/kintoneconnect/issues/9#issuecomment-382833290>,
or mute the thread
